from pathlib import Path

from src.generate.track_yml import read_track_yml


def test_read_track_yml(tmp_path: Path) -> None:
    track_yml_path = tmp_path / "track.yml"
    track_yml_path.write_text(
        """title: "deadlift"

album:
  track_number: 1
  name: "conventional music for the gym"

links:
  youtube: "https://youtu.be/b-Gw5eY1Vxo"
  soundcloud: "https://soundcloud.com/sausageskin/conventional-music-for-the-gym"
  bandcamp: "https://sausageskin.bandcamp.com/track/deadlift"

description: The track was generated by www.udio.com and edited manually in Audacity. The image was generated in ChatGPT.
""",
        encoding="utf-8",
    )

    result = read_track_yml(track_yml_path=track_yml_path)

    assert result.title == "deadlift"
    assert result.album is not None
    assert result.album.track_number == 1
    assert result.album.name == "conventional music for the gym"
    assert result.links is not None
    assert result.links.youtube == "https://youtu.be/b-Gw5eY1Vxo"

    assert (
        result.links.soundcloud
        == "https://soundcloud.com/sausageskin/conventional-music-for-the-gym"
    )

    assert result.links.bandcamp == "https://sausageskin.bandcamp.com/track/deadlift"
    assert "The track was generated" in result.description


def test_read_track_yml_without_quotes(tmp_path: Path) -> None:
    track_yml_path = tmp_path / "track.yml"
    track_yml_path.write_text(
        """title: deadlift
description: Some description without quotes
""",
        encoding="utf-8",
    )

    result = read_track_yml(track_yml_path=track_yml_path)

    assert result.title == "deadlift"
    assert result.description == "Some description without quotes"


def test_read_track_yml_minimal(tmp_path: Path) -> None:
    track_yml_path = tmp_path / "track.yml"
    track_yml_path.write_text(
        """title: "test"
""",
        encoding="utf-8",
    )

    result = read_track_yml(track_yml_path=track_yml_path)

    assert result.title == "test"
    assert result.album is None
    assert result.links is None
    assert result.description is None
